version: '2'

services:
  postgresql:
    image: docker.io/pacloud/postgresql:14
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/pacloud/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'

volumes:
  postgresql_data:
    driver: local
