apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" $ }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-redis-cluster
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis
    - name: redis-cluster
      port: 16379
      targetPort: redis-cluster
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-redis-cluster

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" $ }}-headless
  namespace: redis-cluster
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-redis-cluster
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: redis
    - name: redis-cluster
      port: 16379
      targetPort: redis-cluster
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-redis-cluster